# Generated by Django 2.0.1 on 2018-01-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DileepImage', '0002_addsongmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddSongModel',
            new_name='SongModel',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
