# Generated by Django 2.0.1 on 2018-01-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DileepImage', '0006_auto_20180112_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DileepImage.AlbumModel')),
            ],
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='song_file',
            field=models.FileField(upload_to=''),
        ),
    ]
