# Generated by Django 2.0.1 on 2018-01-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DileepImage', '0008_auto_20180112_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albummodel',
            old_name='image',
            new_name='banner',
        ),
    ]
