# Generated by Django 2.0.1 on 2018-01-14 21:20

import DileepImage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DileepImage', '0009_auto_20180112_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='banner',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=DileepImage.models.bannerloc, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='song_file',
            field=models.FileField(upload_to=DileepImage.models.location),
        ),
    ]
